---
- hosts: all
  become: true
  become_user: root
  tasks:
 # - name: install tomcat
 #   yum: name=tomcat state=present
 # - name: start tomcat
 #   service: name=tomcat state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
 # - name: install git
 #   yum: name=git state=present
 # - name: get repo
 #   git: repo=https://github.com/Sonal0409/dockerdemo.git dest=/tmp/gitrepo
 # - name: Build Dockerfile
#    command: chdir=/tmp/gitrepo docker build -t addressbook:ansible .
  - name: Stop old container if running
    command: docker stop "{{ container_name }}"
    ignore_errors: true
    become_method: sudo
  - name: Delete the stopped container
    command: docker rm "{{ container_name }}"
    ignore_errors: true
    become_method: sudo
  - name: run Image
    command: docker run -d -p "{{ intport }}":"{{ extport }}" --name web "{{ imagename }}":"{{ imageversion }}"
    become_method: sudo
